name 'XavierServers'
maintainer 'Thomas Wimprine'
maintainer_email 'twipmrin@xula.edu'
license 'MIT'
description 'Installs/Configures XavierServers'
long_description 'Installs/Configures XavierServers'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/twimprine/XavierServers/issues'
source_url 'https://github.com/twimprine/XavierServers'

supports 'aix'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'
supports 'windows'

depends 'chef-chef_client_updater'
depends 'chef-client'
depends 'LinuxServer'
depends 'WindowsServer'
